# How much money it costs for each modifier?
# e.g., if the item has the "broken" modifier,
# the final money cost will be: base cost + 10
modifier-cost:
  broken: 10
  shoddy: 10
  weak: 10
  damaged: 10
  keen: 100
  ruthless: 100
  zealous: 100
  hurtful: 100
  strong: 100
  unpleasant: 1000
  demonic: 1000
  superior: 1000
  godly: 1000

# Lore format of cost items for reforge.
reforge-lore:
  - "<dark_gray>重铸材料："
  - "<dark_gray> *{item_cost}"
